version: '3.8'

services:
  backend:
    image: iesgn/temperaturas_backend
    restart: always
    networks:
      - temperaturas-net

  frontend:
    image: iesgn/temperaturas_frontend
    ports:
      - "8081:3000"
    environment:
      - TEMP_SERVER=backend:5000
    depends_on:
      - backend
    restart: always
    networks:
      - temperaturas-net

networks:
  temperaturas-net:
    driver: bridge
